files:
  - source: /app/src/main/res/values/
    ignore:
      - styles.xml
      - themes.xml
      - array*.xml
      - colors.xml
      - dimens.xml
      - keys.xml
      - pref*
      - quarters.xml
      - booleans.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
